# Generated by Django 5.1.4 on 2024-12-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='Saved',
        ),
        migrations.RenameField(
            model_name='saveitem',
            old_name='save',
            new_name='saved',
        ),
    ]
