# Generated by Django 5.1.4 on 2024-12-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site', '0002_rename_save_saved_rename_save_saveitem_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
