# Generated by Django 5.1.4 on 2024-12-21 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site', '0003_post_description_en_post_description_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveitem',
            name='saved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='social_site.saved'),
        ),
    ]
