# Generated by Django 5.1.2 on 2024-12-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_site', '0006_alter_post_image_alter_post_video_alter_story_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='social_site.comment'),
        ),
    ]
