# Generated by Django 5.1.2 on 2024-12-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_site', '0007_alter_commentlike_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
